import React from 'react';
import { BookOpen, Link, Lock, Wallet, Database, Code2, Coins, Users, Shield, LineChart, Globe2, Key } from 'lucide-react';

interface GlossaryTerm {
  icon: any;
  term: string;
  definition: string;
}

const GlossaryCard = ({ icon: Icon, term, definition }: GlossaryTerm) => (
  <div className="bg-white p-8 rounded-xl shadow-sm hover:shadow-md transition-all">
    <div className="bg-emerald-100 w-12 h-12 rounded-lg flex items-center justify-center mb-4">
      <Icon className="h-6 w-6 text-emerald-600" />
    </div>
    <h3 className="text-xl font-semibold mb-3">{term}</h3>
    <p className="text-gray-600 leading-relaxed">{definition}</p>
  </div>
);

const Glossary = () => {
  const terms: GlossaryTerm[] = [
    {
      icon: Database,
      term: "Blockchain",
      definition: "A shared public ledger where all transactions are recorded in chronological order. It secures and verifies OK transactions across all multichain networks."
    },
    {
      icon: Link,
      term: "Multichain",
      definition: "A feature of Okcash that enables integration across multiple blockchain networks, including Ethereum, Binance Smart Chain, Polygon, Avalanche, Arbitrum, Optimism, and more, allowing for seamless cross-chain interactions."
    },
    {
      icon: Lock,
      term: "Staking",
      definition: "Okcash's process of locking OK tokens in staking pools on various networks to earn rewards. By staking, users support network security and contribute to the decentralization of Okcash."
    },
    {
      icon: LineChart,
      term: "LTSS",
      definition: "Long Term Sustainable Staking (LTSS) is the model by which Okcash rewards users who participate in staking. It ensures efficient and secure validation of transactions and long term network growth and stabilization."
    },
    {
      icon: Users,
      term: "OK DAO",
      definition: "The Decentralized Autonomous Organization governing Okcash. OK DAO enables the community to submit proposals, vote on initiatives, and direct the future growth and integrations of Okcash."
    },
    {
      icon: Wallet,
      term: "Web3 Wallets",
      definition: "A digital application that stores and manages Okcash. Web3 Wallets generate unique addresses for users to send, receive, and store their OK tokens securely across multiple networks."
    },
    {
      icon: Coins,
      term: "Staking Pool",
      definition: "A pool where OK holders can lock their tokens to earn rewards. Okcash offers multichain staking pools on networks like BASE, Binance Smart Chain, Polygon, and Avalanche, allowing users to earn high APYs."
    },
    {
      icon: Code2,
      term: "Smart Contract",
      definition: "Self-executing contracts with the terms directly written into code. Okcash utilizes smart contracts on each blockchain network for staking, transfers, and secure, transparent transactions."
    },
    {
      icon: Globe2,
      term: "Transaction",
      definition: "A transfer of OK Token value between wallets that is confirmed by the network and recorded on the selected blockchain. Transactions are fast, secure, and irreversible."
    },
    {
      icon: Database,
      term: "DeFi",
      definition: "Short for Decentralized Finance, an ecosystem of financial applications built on blockchain networks. Okcash's multichain support integrates seamlessly with DeFi protocols across various networks."
    },
    {
      icon: Link,
      term: "Unichain",
      definition: "An upcoming Layer 2 blockchain developed by Uniswap, which Okcash is exploring for potential integration. Unichain focuses on scalability and efficient DeFi transactions."
    },
    {
      icon: Lock,
      term: "OK DAO Treasury",
      definition: "A fund of OK tokens locked until 2026, dedicated to the OK DAO for future development. The Treasury supports community-led proposals and ensures funds via smart contracts for network growth."
    },
    {
      icon: Key,
      term: "Private Key",
      definition: "A secret code linked to your wallet that allows you to sign transactions. It provides proof of ownership and access to your funds. Never share your private key."
    },
    {
      icon: Key,
      term: "Public Key",
      definition: "The public code generated by your wallet that others use to send you OK tokens. It's derived from your private key and can be shared safely. Also called wallet address."
    },
    {
      icon: Shield,
      term: "Team.Finance",
      definition: "A security platform that provides liquidity locks, token locks, and staking services for Okcash, ensuring that staking pools and Treasury funds are secure, transparent, and auditable."
    },
    {
      icon: Link,
      term: "Cross-Chain",
      definition: "Refers to the ability of Okcash to interact across different blockchain networks. This allows users to send, receive, and stake OK on multiple chains, expanding its reach and utility."
    },
    {
      icon: Coins,
      term: "Gas Fees",
      definition: "Fees paid to process transactions on a blockchain. Okcash users pay optimized gas fees depending on the network in use, ensuring efficient and cost-effective transactions."
    },
    {
      icon: Globe2,
      term: "DEX",
      definition: "Short for Decentralized Exchange, a platform for trading cryptocurrencies directly on the blockchain. Okcash is tradable on various DEXs, offering easy, permissionless swaps across networks."
    },
    {
      icon: LineChart,
      term: "APY",
      definition: "Annual Percentage Yield, the rate of return on staked OK tokens. Okcash staking pools on various networks offer competitive APYs, rewarding participants for securing the network."
    },
    {
      icon: Users,
      term: "Multisig",
      definition: "Short for Multi-Signature. A security feature that requires multiple keys to authorize a transaction, ideal for group wallets and the OK DAO's Treasury management."
    }
  ];

  return (
    <section id="glossary" className="py-20 bg-gradient-to-b from-emerald-50 to-white">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <div className="flex items-center justify-center mb-6">
            <BookOpen className="h-12 w-12 text-emerald-600" />
          </div>
          <h2 className="text-4xl font-bold text-gray-900 mb-4">Crypto Glossary</h2>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Essential terminology for understanding the OK ecosystem and blockchain technology.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {terms.map((term, index) => (
            <GlossaryCard
              key={index}
              icon={term.icon}
              term={term.term}
              definition={term.definition}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Glossary;